// <auto-generated />
using AlbumCollection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AlbumCollection.Migrations
{
    [DbContext(typeof(AlbumContext))]
    [Migration("20190310205119_GotRidOfCategoryIds")]
    partial class GotRidOfCategoryIds
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AlbumCollection.Models.Album", b =>
                {
                    b.Property<int>("AlbumId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AlbumImageLocation");

                    b.Property<string>("AlbumName");

                    b.Property<string>("ArtistName");

                    b.HasKey("AlbumId");

                    b.ToTable("Albums");

                    b.HasData(
                        new { AlbumId = 1, AlbumImageLocation = "Img/TheFaithTones.jpg", AlbumName = "Jesus Use Me", ArtistName = "The Faith Tones" },
                        new { AlbumId = 2, AlbumImageLocation = "Img/LeonardNimoy.jpg", AlbumName = "Mr. Spock's Music From Outer Space", ArtistName = "Leonard Nimoy" },
                        new { AlbumId = 3, AlbumImageLocation = "Img/AlanMills.jpg", AlbumName = "Old McDonald Had a Farm", ArtistName = "Alan Mills and the Four Shipmates" }
                    );
                });

            modelBuilder.Entity("AlbumCollection.Models.Song", b =>
                {
                    b.Property<int>("SongId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlbumId");

                    b.Property<string>("SongName");

                    b.HasKey("SongId");

                    b.HasIndex("AlbumId");

                    b.ToTable("Songs");

                    b.HasData(
                        new { SongId = 1, AlbumId = 1, SongName = "Exposed" },
                        new { SongId = 2, AlbumId = 1, SongName = "It's Different Now" },
                        new { SongId = 3, AlbumId = 2, SongName = "Music to Watch Space Girls By" },
                        new { SongId = 4, AlbumId = 2, SongName = "Twinkle, Twinkle Little Earth" },
                        new { SongId = 5, AlbumId = 3, SongName = "I Know an Old Lady" },
                        new { SongId = 6, AlbumId = 3, SongName = "Froggie Went A-Courtin" }
                    );
                });

            modelBuilder.Entity("AlbumCollection.Models.Song", b =>
                {
                    b.HasOne("AlbumCollection.Models.Album")
                        .WithMany("Song")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
