// <auto-generated />
using System;
using AlbumCollection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AlbumCollection.Migrations
{
    [DbContext(typeof(AlbumContext))]
    [Migration("20190310141329_AddedCategoryIds")]
    partial class AddedCategoryIds
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AlbumCollection.Models.Album", b =>
                {
                    b.Property<int>("AlbumId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AlbumId1");

                    b.Property<string>("AlbumImageLocation");

                    b.Property<string>("AlbumName");

                    b.Property<string>("ArtistName");

                    b.Property<int>("CategoryId");

                    b.HasKey("AlbumId");

                    b.HasIndex("AlbumId1");

                    b.ToTable("Albums");

                    b.HasData(
                        new { AlbumId = 1, AlbumImageLocation = "Img/TheFaithTones.jpg", AlbumName = "Jesus Use Me", ArtistName = "The Faith Tones", CategoryId = 1 },
                        new { AlbumId = 2, AlbumImageLocation = "Img/LeonardNimoy.jpg", AlbumName = "Mr. Spock's Music From Outer Space", ArtistName = "Leonard Nimoy", CategoryId = 2 },
                        new { AlbumId = 3, AlbumImageLocation = "Img/AlanMills.jpg", AlbumName = "Old McDonald Had a Farm", ArtistName = "Alan Mills and the Four Shipmates", CategoryId = 3 }
                    );
                });

            modelBuilder.Entity("AlbumCollection.Models.Song", b =>
                {
                    b.Property<int>("SongId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId");

                    b.Property<string>("SongName");

                    b.HasKey("SongId");

                    b.ToTable("Songs");

                    b.HasData(
                        new { SongId = 1, CategoryId = 1, SongName = "Exposed" },
                        new { SongId = 2, CategoryId = 1, SongName = "It's Different Now" },
                        new { SongId = 3, CategoryId = 2, SongName = "Music to Watch Space Girls By" },
                        new { SongId = 4, CategoryId = 2, SongName = "Twinkle, Twinkle Little Earth" },
                        new { SongId = 5, CategoryId = 3, SongName = "I Know an Old Lady" },
                        new { SongId = 6, CategoryId = 3, SongName = "Froggie Went A-Courtin" }
                    );
                });

            modelBuilder.Entity("AlbumCollection.Models.Album", b =>
                {
                    b.HasOne("AlbumCollection.Models.Album")
                        .WithMany("Albums")
                        .HasForeignKey("AlbumId1");
                });
#pragma warning restore 612, 618
        }
    }
}
